worker_processes auto;

events {
    worker_connections 1024;
}

http {

    upstream api_gateway_cluster {
        least_conn;

        server api-gateway:5000 max_fails=3 fail_timeout=30s;

        keepalive 64;
    }

    log_format main '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" '
                    'rt=$request_time urt=$upstream_response_time';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;

    server {
        listen 80;

        client_max_body_size 20M;

        location / {

            proxy_pass http://api_gateway_cluster;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Connection "";

            proxy_connect_timeout 5s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;

            proxy_next_upstream error timeout http_502 http_503 http_504;
            proxy_next_upstream_tries 3;
        }

        location /nginx-health {
            return 200 "NGINX OK";
            add_header Content-Type text/plain;
        }
    }
}